"""empty message

Revision ID: 3b7f0f97aa35
Revises: 
Create Date: 2025-05-09 16:13:48.219426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7f0f97aa35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('risk_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('blood_pressure', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('family_history', sa.Integer(), nullable=True),
    sa.Column('past_high_blood_sugar', sa.Integer(), nullable=True),
    sa.Column('hypertension', sa.Integer(), nullable=True),
    sa.Column('gestational_diabetes', sa.Integer(), nullable=True),
    sa.Column('pcos', sa.Integer(), nullable=True),
    sa.Column('physical_activity', sa.String(length=20), nullable=True),
    sa.Column('smoking', sa.Integer(), nullable=True),
    sa.Column('alcohol', sa.Integer(), nullable=True),
    sa.Column('prediction_result', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_record')
    op.drop_table('user')
    # ### end Alembic commands ###
